AWSTemplateFormatVersion: 2010-09-09
Description: Template to Create an EC2 instance in a VPC
Parameters:
  VpcId:
    Type: String
    Description: VPC id
    Default: vpc-025288340b4162df6
  SubnetId:
    Type: String
    Description: Subnet in which to launch an EC2
    Default: subnet-00a7a3e2466bed6b4
  AvailabilityZone:
    Type: String
    Description: Availability Zone into which instance will launch
    Default: eu-west-2a
  KeyName:
    Description: SSH Keypair to login to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: demokeypair
  MyIpAddress:
    Type: String
    Description: This must be a valid IP address.
    Default: 0.0.0.0/0
    ConstraintDescription: must be a valid IP address of the form x.x.x.x./x
Resources:
  DemoInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      LaunchTemplate:
        LaunchTemplateId: lt-00de45cb32ffd62bb
        Version: 1
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: 0
          SubnetId: !Ref SubnetId
          GroupSet:
            - Ref: WebApplicationServerSG
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-instance'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: a474bede-7128-45bc-8471-514ac4eb2bc2
  WebApplicationServerSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: 'Enable HTTP, HTTPS and SSH access'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-SG'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: !Ref MyIpAddress
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: !Ref MyIpAddress
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref MyIpAddress
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8082
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: !Ref MyIpAddress
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: '0'
          ToPort: '65535'
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f22f7652-c97d-4d11-8672-1b19872bd55f
Outputs:
  DemoInstanceId:
    Description: Instance Id
    Value: !Ref DemoInstance
Metadata:
  'AWS::CloudFormation::Designer':
    a474bede-7128-45bc-8471-514ac4eb2bc2:
      size:
        width: 60
        height: 60
      position:
        x: 180
        'y': 90
      z: 1
      embeds: []
      isassociatedwith:
        - ec51147b-d31f-474b-a667-1d50babd3b4d
        - f22f7652-c97d-4d11-8672-1b19872bd55f
    f22f7652-c97d-4d11-8672-1b19872bd55f:
      size:
        width: 60
        height: 60
      position:
        x: 270
        'y': 90
      z: 1
      embeds: []
