version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - chmod +x gradlew
      - ./gradlew clean build buildZip
  post_build:
    commands:
      - echo Build completed on $(date --utc '+%Y-%m-%dT%H:%M:%S')
artifacts:
  files:
    - build/libs/awsinfo-0.0.1-SNAPSHOT.jar
    - lambda/build/distributions/lambda-0.0.1-SNAPSHOT.zip
  discard-paths: yes